-- MySQL Script generated by MySQL Workbench
-- Sat Feb 11 17:59:44 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema email_validation_dB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema email_validation_dB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `email_validation_dB` DEFAULT CHARACTER SET utf8 ;
USE `email_validation_dB` ;

-- -----------------------------------------------------
-- Table `email_validation_dB`.`user_email`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `email_validation_dB`.`user_email` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
