-- MySQL Script generated by MySQL Workbench
-- Tue Jul 18 21:13:03 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema projectBoard
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projectBoard
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projectBoard` DEFAULT CHARACTER SET utf8 ;
USE `projectBoard` ;

-- -----------------------------------------------------
-- Table `projectBoard`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectBoard`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `email` VARCHAR(255) NULL,
  `birthday` DATETIME NULL,
  `password` VARCHAR(255) NULL,
  `salt` VARCHAR(45) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectBoard`.`projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectBoard`.`projects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `deadline` DATETIME NULL,
  `description` TEXT NULL,
  `status` VARCHAR(45) NULL,
  `dateCompleted` DATETIME NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
