# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-26 02:14
from __future__ import unicode_literals

import apps.regForm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regForm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=45, validators=[apps.regForm.models.validateName]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=45, validators=[apps.regForm.models.validateName]),
        ),
    ]
