# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-26 02:26
from __future__ import unicode_literals

import apps.regForm.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regForm', '0002_auto_20170826_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50, validators=[apps.regForm.models.validatePass]),
        ),
    ]
