# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 04:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20170224_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='liker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_this', to='first_app.User'),
        ),
        migrations.AlterField(
            model_name='like',
            name='worthySecret',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='first_app.Secret'),
        ),
    ]
