# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20170227_0443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='liker',
        ),
        migrations.AddField(
            model_name='like',
            name='liker',
            field=models.ManyToManyField(related_name='liked_this', to='first_app.User'),
        ),
    ]
