# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 00:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20170301_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='r_content',
            name='review_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_content', to='first_app.Review'),
        ),
    ]
