# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20170301_0058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='r_content',
            name='review_id',
        ),
        migrations.AddField(
            model_name='review',
            name='content',
            field=models.TextField(default='hello', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='R_Content',
        ),
    ]
