# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-30 19:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_auto_20170830_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pokemon',
            field=models.ManyToManyField(to='first_app.Pokemon'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 30, 19, 15, 31, 500336)),
        ),
    ]
