# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-26 22:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('add_course', '0002_auto_20170726_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_description', to='add_course.Course'),
        ),
    ]
