# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-25 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_auto_20170825_1904'),
        ('add_course', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='users',
            field=models.ManyToManyField(to='first_app.User'),
        ),
    ]
