# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20170224_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='user_creator_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='made_trip', to='first_app.User'),
        ),
    ]
