-- MySQL Script generated by MySQL Workbench
-- Tue Jul 18 14:25:51 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema books_and_quotes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema books_and_quotes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `books_and_quotes` DEFAULT CHARACTER SET utf8 ;
USE `books_and_quotes` ;

-- -----------------------------------------------------
-- Table `books_and_quotes`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `books_and_quotes`.`books` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL,
  `author` VARCHAR(255) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `books_and_quotes`.`quotes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `books_and_quotes`.`quotes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `book_id` INT NOT NULL,
  `quote` TEXT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_quotes_books_idx` (`book_id` ASC),
  CONSTRAINT `fk_quotes_books`
    FOREIGN KEY (`book_id`)
    REFERENCES `books_and_quotes`.`books` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
